# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('estado_servicio', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20, verbose_name='Estado del servicio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_edita', models.DateTimeField(auto_now=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
                ('usuario_edita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_principal_editados', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_principal_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_principal_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
