# Generated by Django 4.2.29 on 2026-03-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado_servicio',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', help_text='Independiente de estado. 1=activo para uso, 0=inactivo (ej. oculto o deshabilitado). El frontend lo gestiona en edición.', max_length=20),
        ),
    ]
