# Generated by Django 4.2.29

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def set_estado_producto_from_activo(apps, schema_editor):
    Producto = apps.get_model('producto', 'Producto')
    for p in Producto.objects.all():
        p.estado_producto = '1' if p.activo else '0'
        p.save(update_fields=['estado_producto'])


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(
                choices=[('1', 'Activo'), ('0', 'Inactivo')],
                default='1',
                max_length=20,
                verbose_name='Estado producto',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_registra',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_registra',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos_registrados',
                to='persona.persona',
                verbose_name='Usuario registra',
            ),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos_actualizados',
                to='persona.persona',
                verbose_name='Actualizado por',
            ),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_elimina',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_elimina',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos_eliminados',
                to='persona.persona',
                verbose_name='Usuario elimina',
            ),
        ),
        migrations.RunPython(set_estado_producto_from_activo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
