# Generated by Django 4.2.29 on 2026-03-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_estado_estado_producto_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', help_text='Independiente de estado. 1=activo para uso, 0=inactivo (ej. deshabilitado). El frontend lo gestiona en edición.', max_length=20, verbose_name='Estado producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_elimina',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
