# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Select'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('textarea', 'Área de texto')], max_length=20)),
                ('producto', models.CharField(blank=True, default='', help_text='Valor de la opción del campo Producto al que pertenece este campo (opciones de otro campo).', max_length=255)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('seccion', models.CharField(choices=[('cliente', 'Cliente'), ('datos_base', 'Datos base'), ('campos_formulario', 'Campos del formulario'), ('vendedor', 'Vendedor')], default='campos_formulario', help_text='Sección del formulario a la que pertenece el campo.', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible_si', models.CharField(blank=True, default='', help_text='Condición opcional para mostrar el campo según el valor de otro (uso futuro).', max_length=500)),
                ('requerido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, editable=False, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='formularios.campo')),
            ],
            options={
                'verbose_name': 'Opción de campo',
                'verbose_name_plural': 'Opciones de campo',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
