# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Select'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('textarea', 'Área de texto')], max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('default_value', models.CharField(blank=True, default='', max_length=500)),
                ('visible_si', models.CharField(blank=True, default='', help_text='Condición opcional para mostrar el campo según el valor de otro (uso futuro).', max_length=500)),
                ('requerido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos_formulario', to='empresa.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos_formulario', to='servicio.servicio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='formularios.campo')),
            ],
            options={
                'verbose_name': 'Opción de campo',
                'verbose_name_plural': 'Opciones de campo',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
