# Generated by Django 4.2.29 on 2026-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Select'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('textarea', 'Área de texto'), ('radio', 'Radio button'), ('multiselect', 'Selección múltiple')], max_length=20),
        ),
    ]
