# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratista', '0002_initial'),
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoopcion',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campo_opciones_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario elimina'),
        ),
        migrations.AddField(
            model_name='campoopcion',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campo_opciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registra'),
        ),
        migrations.AddField(
            model_name='campo',
            name='contratista',
            field=models.ForeignKey(blank=True, help_text='Si es null, aplica a todos los contratistas del servicio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campos_formulario', to='contratista.contratista'),
        ),
        migrations.AddField(
            model_name='campo',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Si es null, aplica a todos los servicios.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campos_formulario', to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='campo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='campo',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario elimina'),
        ),
        migrations.AddField(
            model_name='campo',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_formulario_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registra'),
        ),
    ]
