# Generated by Django 4.2.29 on 2026-03-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_alter_campo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Select'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('textarea', 'Área de texto')], max_length=20),
        ),
    ]
