# Generated by Django 4.2.29 on 2026-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_add_campo_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('textarea', 'Área de texto'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('entity_select', 'Selector de entidad')], max_length=20),
        ),
    ]
