# Generated by Django 4.2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_add_estado_empresa'),
        ('formularios', '0003_alter_campo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='campos_formulario',
                to='empresa.empresa',
                help_text='Si es null, el campo aplica a todas las empresas del servicio.',
            ),
        ),
    ]
