# Generated by Django 4.2 on 2026-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_campo_empresa_nullable_aplicar_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='producto',
            field=models.CharField(blank=True, default='', help_text='Valor de la opción del campo Producto al que pertenece este campo (opciones de otro campo).', max_length=255),
        ),
    ]
