# Generated by Django 4.2.29 on 2026-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_campo_estandarizar_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoopcion',
            name='fecha_registra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
