# Generated by Django 4.2.29 on 2026-03-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_add_campo_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='help_text',
        ),
    ]
