# Generated by Django 4.2.29 on 2026-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_remove_campo_default_value_remove_campo_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='visible_si',
            field=models.JSONField(blank=True, default=None, help_text='Condición opcional para mostrar el campo según el valor de otro (objeto JSON o null). En BD es jsonb.', null=True),
        ),
    ]
