# Generated by Django 4.2.29 on 2026-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0012_alter_campo_visible_si'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='seccion',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('datos_base', 'Datos base'), ('campos_formulario', 'Campos del formulario'), ('vendedor', 'Comercial')], default='campos_formulario', help_text='Sección del formulario a la que pertenece el campo.', max_length=30),
        ),
    ]
