# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10)),
                ('identificacion', models.CharField(db_index=True, max_length=50)),
                ('primer_nombre', models.CharField(blank=True, max_length=150)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100)),
                ('primer_apellido', models.CharField(blank=True, max_length=150)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('correo_auth', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario'), ('cliente', 'Cliente'), ('invitado', 'Invitado')], default='usuario', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('codigo_verificado', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_identificacion', models.CharField(db_index=True, max_length=50)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('estado_vendedor', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20, verbose_name='Estado vendedor')),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario_elimina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario elimina')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registra')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['-fecha_registra'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendedor',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_elimina__isnull', True)), fields=('tipo_identificacion', 'numero_identificacion'), name='vendedor_tipo_num_id_uniq_activo'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion', 'identificacion'), name='persona_tipo_id_identificacion_uniq'),
        ),
    ]
