# Generated by Django 4.2.29 on 2026-03-04 23:06

from django.db import migrations, models


def rellenar_campos_desde_auth(apps, schema_editor):
    Persona = apps.get_model('persona', 'Persona')
    for p in Persona.objects.all():
        if not p.primer_nombre and p.first_name:
            p.primer_nombre = p.first_name
        if not p.primer_apellido and p.last_name:
            p.primer_apellido = p.last_name
        if not p.correo and p.email:
            p.correo = p.email
        if p.created_at is None and p.date_joined:
            p.created_at = p.date_joined
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='persona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(rellenar_campos_desde_auth, migrations.RunPython.noop),
    ]
