# Generated by Django 4.2.29 on 2026-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_add_primer_nombre_primer_apellido_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo_auth',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20),
        ),
    ]
