# Generated by Django 4.2.29 on 2026-03-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_vendedor_estandarizar_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['-fecha_registra'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
