# Generated by Django 4.2.29 on 2026-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_alter_vendedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10),
        ),
    ]
