# Generated by Django 4.2.29 on 2026-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_alter_persona_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(choices=[('NIE', 'NIE - NÚMERO DE IDENTIFICACIÓN EXTRANJERO'), ('PAS', 'PAS - PASAPORTE'), ('DNI', 'DNI - DOCUMENTO NACIONAL DE IDENTIDAD'), ('CIF', 'CIF - CÓDIGO DE IDENTIFICACIÓN FISCAL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('NIE', 'NIE - NÚMERO DE IDENTIFICACIÓN EXTRANJERO'), ('PAS', 'PAS - PASAPORTE'), ('DNI', 'DNI - DOCUMENTO NACIONAL DE IDENTIDAD'), ('CIF', 'CIF - CÓDIGO DE IDENTIFICACIÓN FISCAL')], max_length=10),
        ),
    ]
