# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('estado_contratista', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', help_text='Independiente de estado. 1=activo para uso, 0=inactivo (ej. oculto o deshabilitado). El frontend lo gestiona en edición.', max_length=20, verbose_name='Estado del contratista')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_edita', models.DateTimeField(auto_now=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['nombre'],
            },
        ),
    ]
