# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratistas', to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='contratista',
            name='usuario_edita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratistas_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratista',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratistas_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratista',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratistas_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
