# Generated by Django 4.2+ for app relaciones

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_tipo', models.CharField(
                    choices=[
                        ('servicio', 'Servicio'),
                        ('contratista', 'Contratista'),
                        ('producto', 'Producto'),
                        ('campo', 'Campo'),
                        ('vendedor', 'Vendedor'),
                    ],
                    max_length=20,
                    verbose_name='Tipo de entidad origen',
                )),
                ('origen_id', models.PositiveIntegerField(verbose_name='ID entidad origen')),
                ('destino_tipo', models.CharField(
                    choices=[
                        ('servicio', 'Servicio'),
                        ('contratista', 'Contratista'),
                        ('producto', 'Producto'),
                        ('campo', 'Campo'),
                        ('vendedor', 'Vendedor'),
                    ],
                    max_length=20,
                    verbose_name='Tipo de entidad destino',
                )),
                ('destino_id', models.PositiveIntegerField(verbose_name='ID entidad destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Relación',
                'verbose_name_plural': 'Relaciones',
                'ordering': ['origen_tipo', 'origen_id', 'destino_tipo', 'destino_id'],
            },
        ),
        migrations.AddIndex(
            model_name='relacion',
            index=models.Index(fields=['origen_tipo', 'origen_id'], name='rel_origen_idx'),
        ),
        migrations.AddIndex(
            model_name='relacion',
            index=models.Index(fields=['destino_tipo', 'destino_id'], name='rel_destino_idx'),
        ),
    ]
