# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_identificacion', models.CharField(blank=True, db_index=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('contratista_id', models.PositiveIntegerField(blank=True, help_text='ID del contratista seleccionado al crear el cliente', null=True)),
                ('producto', models.CharField(blank=True, default='', help_text='Producto seleccionado al completar el cliente', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.CharField(blank=True, default='', max_length=255)),
                ('formulario_id', models.PositiveIntegerField(blank=True, help_text='Referencia a formulario/campo si aplica', null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente empresa',
                'verbose_name_plural': 'Cliente empresas',
                'ordering': ['-fecha_registra'],
            },
        ),
        migrations.CreateModel(
            name='FormularioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=255)),
                ('respuesta_campo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta formulario cliente',
                'verbose_name_plural': 'Respuestas formulario cliente',
                'ordering': ['cliente', 'nombre_campo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(help_text='Valor del estado de venta: pendiente, completada, etc.', max_length=50)),
                ('estado_registro', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', help_text='1=activo, 0=eliminado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_venta', to='cliente.cliente')),
                ('cliente_empresa', models.ForeignKey(blank=True, help_text='Producto específico. Si es null, aplica al cliente (legacy).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_venta', to='cliente.clienteempresa')),
            ],
            options={
                'verbose_name': 'Historial estado de venta',
                'verbose_name_plural': 'Historial estados de venta',
                'ordering': ['-fecha_registra'],
            },
        ),
    ]
