# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0009_vendedor_estado_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_identificacion', models.CharField(blank=True, db_index=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tipo_cliente', models.CharField(choices=[('2', 'Empresa'), ('1', 'Particular')], default='2', max_length=2)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('estado_venta', models.CharField(blank=True, choices=[('completada', 'Venta completada'), ('cancelada', 'Venta cancelada'), ('pospuesta', 'Venta pospuesta'), ('pendiente', 'Venta pendiente')], default='pendiente', max_length=50)),
                ('servicio_id', models.PositiveIntegerField(blank=True, help_text='ID del servicio seleccionado al crear el cliente', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
                ('usuario_elimina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_registrados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='persona.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FormularioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=255)),
                ('respuesta_campo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('fecha_elimina', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='cliente.cliente')),
                ('usuario_elimina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulario_cliente_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulario_cliente_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta formulario cliente',
                'verbose_name_plural': 'Respuestas formulario cliente',
                'ordering': ['cliente', 'nombre_campo'],
                'unique_together': {('cliente', 'nombre_campo')},
            },
        ),
    ]
