# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratista', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoventa',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_estado_venta_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadoventa',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_estado_venta_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulariocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='formulariocliente',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulario_cliente_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulariocliente',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulario_cliente_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_empresas', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresas', to='contratista.contratista'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresas', to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_empresas_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_empresas', to='persona.vendedor', verbose_name='Vendedor del producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_elimina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formulariocliente',
            unique_together={('cliente', 'nombre_campo')},
        ),
    ]
