# Generated by Django 4.2 on 2026-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_backfill_estado_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='producto',
            field=models.CharField(blank=True, default='', help_text='Producto seleccionado al completar el cliente', max_length=255),
        ),
    ]
