# Generated by Django 4.2.29 on 2026-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_add_estado_registro_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoventa',
            name='estado',
            field=models.CharField(help_text='Valor del estado de venta: pendiente, completada, etc.', max_length=50),
        ),
    ]
