# Generated by Django 4.2 on 2026-03-13 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_add_estado_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicio', '0002_servicio_estado_servicio'),
        ('cliente', '0006_add_estado_registro_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoventa',
            name='estado',
            field=models.CharField(help_text='Valor del estado de venta: pendiente, completada, etc.', max_length=50),
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.CharField(blank=True, default='', max_length=255)),
                ('formulario_id', models.PositiveIntegerField(blank=True, help_text='Referencia a formulario/campo si aplica', null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=20)),
                ('fecha_registra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_empresas', to='cliente.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresas', to='empresa.empresa')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresas', to='servicio.servicio')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_empresas_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente empresa',
                'verbose_name_plural': 'Cliente empresas',
                'ordering': ['-fecha_registra'],
            },
        ),
    ]
