# Generated by Django 4.2.29 on 2026-03-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_add_cliente_empresa'),
        ('cliente', '0007_alter_historialestadoventa_estado'),
    ]

    operations = [
    ]
