# Generated by Django 4.2 on 2026-03-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_merge_20260313_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoventa',
            name='cliente_empresa',
            field=models.ForeignKey(blank=True, help_text='Producto específico. Si es null, aplica al cliente (legacy).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_venta', to='cliente.clienteempresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('DNI', 'DNI'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso provisional de trabajo'), ('OTRO', 'Otro')], max_length=10),
        ),
    ]
