# Generated by Django 4.2 on 2026-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_add_cliente_empresa_to_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
