# Generated by Django 4.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_ensure_clienteempresa_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cups',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
