# Generated by Django 4.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_add_cups_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='compania_anterior',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='compania_actual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
