# Generated by Django 4.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_add_compania_anterior_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico_o_carta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
