# Generated by Django 4.2 on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_add_correo_electronico_o_carta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo_electronico_o_carta',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='correo_electronico_o_carta',
        ),
    ]
