# Generated by Django 4.2.29 on 2026-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_rename_correo_to_correo_electronico_o_carta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico_o_carta',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
