# Generated by Django 4.2.29 on 2026-03-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_alter_persona_tipo_identificacion_and_more'),
        ('cliente', '0020_add_cerrador_to_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('NIE', 'NIE - NÚMERO DE IDENTIFICACIÓN EXTRANJERO'), ('PAS', 'PAS - PASAPORTE'), ('DNI', 'DNI - DOCUMENTO NACIONAL DE IDENTIDAD'), ('CIF', 'CIF - CÓDIGO DE IDENTIFICACIÓN FISCAL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clienteempresa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_empresas', to='persona.vendedor', verbose_name='Comercial'),
        ),
    ]
